export enum TEST_ASYNC_ACTION {
    GET_NAME = 'TEST_ASYNC_ACTION_GET_NAME',
    GET_DETAIL = 'TEST_ASYNC_ACTION_GET_DETAIL',
}
export enum TEST_ACTION {
    SET_NAME = 'ACCOUNT_ACTION_SET_INFO',
    SET_DETAIL = 'ACCOUNT_ACTION_SET_DETAIL',
    SET_ERROR = 'ACCOUNT_ACTION_SET_ERRPR',
}
